/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iq_selector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(054e052b1e65b870ce18acd76d354022)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dmr/iq_selector.h>
// pydoc.h is automatically generated in the build directory
#include <iq_selector_pydoc.h>

void bind_iq_selector(py::module& m)
{

    using iq_selector    = gr::dmr::iq_selector;


    py::class_<iq_selector, gr::block, gr::basic_block,
        std::shared_ptr<iq_selector>>(m, "iq_selector", D(iq_selector))

        .def(py::init(&iq_selector::make),
           D(iq_selector,make)
        )
        



        ;




}








